apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: practice-project

data:
  PORT: "5000"
  DB_HOST: "practice-project-dev-postgres.c3ug6gwked2r.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "appdb"  