apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-deployment
  namespace: practice-project

  labels:
    app: database

spec:
  replicas: 1 

  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: database

          image: postgres:16-alpine

          ports:
            - containerPort: 5432 

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage 
              mountPath: /var/lib/postgresql/data 

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "500m"

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            failureThreshold: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5 

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 5

      volumes:
        - name: postgres-storage 
          persistentVolumeClaim:
            claimName: postgres-pvc 