name: Build and Push Images

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  BACKEND_ECR_REPOSITORY: practice-project-dev-backend
  FRONTEND_ECR_REPOSITORY: practice-project-dev-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push backend image
        run: |
          docker build -t $BACKEND_ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker tag $BACKEND_ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG
          docker tag $BACKEND_ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$BACKEND_ECR_REPOSITORY:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$BACKEND_ECR_REPOSITORY:latest

      - name: Build and push frontend image
        run: |
          docker build -t $FRONTEND_ECR_REPOSITORY:$IMAGE_TAG ./frontend
          docker tag $FRONTEND_ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG
          docker tag $FRONTEND_ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_ECR_REPOSITORY:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_ECR_REPOSITORY:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Check cluster access
        run: |
         kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
         kubectl apply -R -f k8s/eks/

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment/backend-deployment -n practice-project
          kubectl rollout restart deployment/frontend-deployment -n practice-project

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/backend-deployment -n practice-project --timeout=300s
          kubectl rollout status deployment/frontend-deployment -n practice-project --timeout=300s